services:
  $mysql-database:
    image: mariadb:10.6
    container_name: $mysql-database
    restart: always
    ports:
      - "$mysql-port:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $mysql-root-password
      MYSQL_DATABASE: $mysql-database
      MYSQL_USER: $mysql-user
      MYSQL_PASSWORD: $mysql-password
    volumes:
      - $mysql-database:/var/lib/mysql
    networks:
      - autohost_net

  $service-name:
    image: nextcloud
    container_name: $service-name
    restart: always
    ports:
      - "$port:80"
    environment:
      MYSQL_DATABASE: $mysql-database
      MYSQL_USER: $mysql-user
      MYSQL_PASSWORD: $mysql-password
      MYSQL_HOST: $mysql-database
    depends_on:
      - $mysql-database
    volumes:
      - $service-name:/var/www/html
    networks:
      - autohost_net

volumes:
  $mysql-database:
  $service-name:

networks:
  autohost_net:
    external: true
