services:
  $mysql-database:
    image: mariadb:10.6
    container_name: $mysql-database
    restart: unless-stopped
    ports:
      - "$mysql-port:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $mysql-root-password
      MYSQL_DATABASE: $mysql-database
      MYSQL_USER: $mysql-user
      MYSQL_PASSWORD: $mysql-password
    volumes:
      - $mysql-database:/var/lib/mysql
    networks:
      - autohost_net

  $service-name:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: $service-name
    depends_on:
      - $mysql-database
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Mexico_City
      APP_URL: http://localhost:$port
      APP_KEY: $app-key
      DB_HOST: $mysql-database
      DB_PORT: $mysql-port
      DB_USERNAME: $mysql-user
      DB_PASSWORD: $mysql-password
      DB_DATABASE: $mysql-database
    volumes:
      - $service-name:/config
    ports:
      - $port:80
    restart: unless-stopped
    networks:
      - autohost_net

volumes:
  $mysql-database:
  $service-name:

networks:
  autohost_net:
    external: true
