

[cloudflare]
download_url = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
install_path = "/usr/local/bin/cloudflared"

[caddy]
gpg_key_url   = "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
repo_list_url = "https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt"
package_name  = "caddy"
service_name  = "caddy"